[
  {
    "enable": true,
    "phone": "18172567201",
    "password": "Aa932870333",
    "keepLogin": false,
    "token": "如果keepLogin为false就不填",
    "userId": "如果keepLogin为false就不填",
    "planId": "如果keepLogin为false就不填",
    "randomLocation": true,
    "user-agent": "null",
    "signCheck": false,
    "country": "中国",
    "province": "广西壮族自治区",
    "city": "北流市",
    "area": "北流市",
    "desc": "备注",
    "type": "android",
    "address": "北流市妇幼保健院",
    "longitude": "110.3539890",
    "latitude": "22.7132195",
    "pushKey": "67583f09cd9440c58fded1bc12343060"
  }
]
